hello: hello.h hello.m BehaivourAlpha.h BehaivourAlpha.m
	gcc `gnustep-config --objc-flags` -lgnustep-base hello.m -o hello



clean:
	rm hello	
	rm *.d

environment:
	. /usr/share/GNUstep/Makefiles/GNUstep.sh
