strategy_client: strategy_client.h strategy_client.m FlyBehaviour.h FlyBehaviour.m
	gcc `gnustep-config --objc-flags` -lgnustep-base strategy_client.m -o strategy_client



clean:
	rm strategy_client	
	rm *.d

environment:
	. /usr/share/GNUstep/Makefiles/GNUstep.sh
