<?php
require_once 'PHPUnit/Framework.php';

require_once 'Strategy/StrategyClient.php';

/**
 * Test class for StrategyClient.
 * Generated by PHPUnit on 2010-12-19 at 18:17:42.
 */
class StrategyClientTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var StrategyClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StrategyClient;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testRun().
     */
    public function testRun()
    {
	    $this->object->Run();
    }
}
?>
